[package]
name = "html-parser"
version = "0.1.0"
edition = "2021"
description = "An HTML document parser"

[dependencies]
# Core
scraper = "0.13"
select = "0.5"
structopt = "0.3"

# Data
bytes = "1.1.0"

# Utils
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
